org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2

forge_gradle_version=2.3.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

mod_id=mobarmory
mod_name=Mob Armory
mod_version=1.1
mod_author=["Estie"]
mod_group_id=com.estie.mobarmory
mod_description=Adds equipment sets to mobs, letting them select from multiple loadouts based on the type, biome, difficulty etc.